node {
  stage 'Checkout'
  checkout scm'


  stage 'SonarQube analysis'
    // requires SonarQube Scanner 2.8+
    def scannerHome = tool 'sonarScanner';
  withSonarQubeEnv('sonarQube') {
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }

